pull_request_rules:
  - name: Require approval from UHS maintainers
    conditions:
      - "#approved-reviews-by>=1"
    actions:
      post_check:
        success_conditions:
          - or:
              - "#approved-reviews-by>=2"
              - and:
                  - "#approved-reviews-by>=1"
                  - "author~=^(dave[-]gantenbein|dejanzele|richscott|nikola[-]jokic|sudiptob2|dcoric|fabiovincenzi|pavlovic[-]ivan)"
        title:
          Two are checks required.
